### ISSUE TITLE
centos-ci: can we use the centos-ci to test PRs here?

### ISSUE THREAD

**Issue by obnoxxx** [heketi/ci-tests#3]
Could we use a variant of the centos-ci for heketi (with a script modification as proposed in a PR to this repo) to test the change before we merge it?

**Comment by nixpanic** [comment]
@obnoxxx can you assign this to me? I do not have the permissions to do so.

**Comment by phlogistonjohn** [comment]
Closing open items to prepare for archiving heketi/ci-tests
